[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

lib_deps =
    esphome/ESP32-audioI2S
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer
    bblanchon/ArduinoJson @ ^6.19.4
    adafruit/Adafruit NeoPixel @ ^1.11.0

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
