// DDNSManager.cpp
#include "DDNSManager.h"
#include <Preferences.h>
#include <WiFi.h>
#include <HTTPClient.h>
#include <base64.h>

#include <WiFiClientSecure.h>

DDNSManager ddnsManager;

void DDNSManager::begin() {
    loadConfig();
    _lastUpdate = 0;
}

void DDNSManager::loadConfig() {
    Preferences prefs;
    prefs.begin("ddns", true);
    _enabled = prefs.getBool("enabled", false);
    _domain = prefs.getString("domain", "");
    _user = prefs.getString("user", "");
    _pass = prefs.getString("pass", "");
    prefs.end();
}

void DDNSManager::forceUpdate() {
    loadConfig();
    if (_enabled) performUpdate();
}

void DDNSManager::loop() {
    if (!_enabled || WiFi.status() != WL_CONNECTED) return;
    
    if (millis() - _lastUpdate >= UPDATE_INTERVAL || _lastUpdate == 0) {
        performUpdate();
    }
}

void DDNSManager::performUpdate() {
    _lastUpdate = millis();

    if (_domain.length() == 0 || _user.length() == 0) {
        Serial.println("[DDNS] Update skipped: Domain or Username is empty.");
        return;
    }
    
    Serial.printf("[DDNS] Starting update for: %s\n", _domain.c_str());
    
    String auth = _user + ":" + _pass;
    String authEncoded = base64::encode(auth);
    // Remove newlines generated by base64::encode
    authEncoded.replace("\r", "");
    authEncoded.replace("\n", "");
    
    int httpCode = -1;
    String payload = "";
    
    // First attempt: HTTPS
    {
        Serial.println("[DDNS] Trying HTTPS update...");
        WiFiClientSecure secureClient;
        secureClient.setInsecure();
        
        HTTPClient http;
        String url = "https://dynupdate.no-ip.com/nic/update?hostname=" + _domain;
        http.setTimeout(5000);
        http.begin(secureClient, url);
        
        http.addHeader("Authorization", "Basic " + authEncoded);
        http.addHeader("User-Agent", "VivoSmart/3.0 admin@example.com");
        
        httpCode = http.GET();
        if (httpCode > 0) {
            payload = http.getString();
            Serial.printf("[DDNS] HTTPS Response: Code %d, Payload: %s\n", httpCode, payload.c_str());
        } else {
            Serial.printf("[DDNS] HTTPS Failed: %s\n", http.errorToString(httpCode).c_str());
        }
        http.end();
    }
    
    if (httpCode <= 0) {
        Serial.println("[DDNS] HTTPS failed, will retry later");
    }
    
}
